name: Deploy CDK Stack

##########################################################################################################
####                                BRANCHES TO DEPLOY TO
####        however, the filters in the last section select which branches to deploy to

##########################################################################################################

on:
  push:
    branches:
      - main

##########################################################################################################
####      THE JOBS BELOW ARE PERFORMED ON THE GITHUB WORKFLOW RUNNER (UBUNTU-LATEST)

##########################################################################################################

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js (required by CDK)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'


      # Install AWS CDK globally
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # Install @react-google-maps/api
      - name: Install @react-google-maps/api
        run: npm install @react-google-maps/api

##########################################################################################################
#####                   SECRETS FOR AWS CREDENTIALS
#####       secrets need to be created in the github repository
#####       https://docs.github.com/en/actions/security-guides/encrypted-secrets
##### https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository

##########################################################################################################
      - name: Deploy CDK Stack
        env:
          AWS_REGION: us-east-1
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLEMAPSAPIKEY: ${{ secrets.GOOGLEMAPSAPIKEY }}
        run: |
          npx cdk deploy --require-approval never
